/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsVideoIdeasRouteImport } from './routes/tools.video-ideas'
import { Route as ToolsTrendAnglesRouteImport } from './routes/tools.trend-angles'
import { Route as ToolsThumbnailTextRouteImport } from './routes/tools.thumbnail-text'
import { Route as ToolsThumbnailDesignerRouteImport } from './routes/tools.thumbnail-designer'
import { Route as ToolsStorytimeBuilderRouteImport } from './routes/tools.storytime-builder'
import { Route as ToolsSponsorshipPitchRouteImport } from './routes/tools.sponsorship-pitch'
import { Route as ToolsSeriesNamerRouteImport } from './routes/tools.series-namer'
import { Route as ToolsSeoDescriptionRouteImport } from './routes/tools.seo-description'
import { Route as ToolsScriptWriterRouteImport } from './routes/tools.script-writer'
import { Route as ToolsRetentionDoctorRouteImport } from './routes/tools.retention-doctor'
import { Route as ToolsRepurposingAssistantRouteImport } from './routes/tools.repurposing-assistant'
import { Route as ToolsRateCardCalculatorRouteImport } from './routes/tools.rate-card-calculator'
import { Route as ToolsPinnedCommentRouteImport } from './routes/tools.pinned-comment'
import { Route as ToolsPhotoCarouselRouteImport } from './routes/tools.photo-carousel'
import { Route as ToolsPacingCheckerRouteImport } from './routes/tools.pacing-checker'
import { Route as ToolsNicheFinderRouteImport } from './routes/tools.niche-finder'
import { Route as ToolsMediaKitBuilderRouteImport } from './routes/tools.media-kit-builder'
import { Route as ToolsLoopCtaBuilderRouteImport } from './routes/tools.loop-cta-builder'
import { Route as ToolsHookRewriterRouteImport } from './routes/tools.hook-rewriter'
import { Route as ToolsHookGeneratorRouteImport } from './routes/tools.hook-generator'
import { Route as ToolsHookAbTesterRouteImport } from './routes/tools.hook-ab-tester'
import { Route as ToolsHashtagPackRouteImport } from './routes/tools.hashtag-pack'
import { Route as ToolsDuetStitchFinderRouteImport } from './routes/tools.duet-stitch-finder'
import { Route as ToolsContentCalendarRouteImport } from './routes/tools.content-calendar'
import { Route as ToolsCommentReplyGeneratorRouteImport } from './routes/tools.comment-reply-generator'
import { Route as ToolsCaptionCrafterRouteImport } from './routes/tools.caption-crafter'
import { Route as ToolsBioOptimizerRouteImport } from './routes/tools.bio-optimizer'
import { Route as ToolsBestTimeToPostRouteImport } from './routes/tools.best-time-to-post'
import { Route as ToolsBRollSuggesterRouteImport } from './routes/tools.b-roll-suggester'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsVideoIdeasRoute = ToolsVideoIdeasRouteImport.update({
  id: '/tools/video-ideas',
  path: '/tools/video-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTrendAnglesRoute = ToolsTrendAnglesRouteImport.update({
  id: '/tools/trend-angles',
  path: '/tools/trend-angles',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsThumbnailTextRoute = ToolsThumbnailTextRouteImport.update({
  id: '/tools/thumbnail-text',
  path: '/tools/thumbnail-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsThumbnailDesignerRoute = ToolsThumbnailDesignerRouteImport.update({
  id: '/tools/thumbnail-designer',
  path: '/tools/thumbnail-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsStorytimeBuilderRoute = ToolsStorytimeBuilderRouteImport.update({
  id: '/tools/storytime-builder',
  path: '/tools/storytime-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSponsorshipPitchRoute = ToolsSponsorshipPitchRouteImport.update({
  id: '/tools/sponsorship-pitch',
  path: '/tools/sponsorship-pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSeriesNamerRoute = ToolsSeriesNamerRouteImport.update({
  id: '/tools/series-namer',
  path: '/tools/series-namer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSeoDescriptionRoute = ToolsSeoDescriptionRouteImport.update({
  id: '/tools/seo-description',
  path: '/tools/seo-description',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsScriptWriterRoute = ToolsScriptWriterRouteImport.update({
  id: '/tools/script-writer',
  path: '/tools/script-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRetentionDoctorRoute = ToolsRetentionDoctorRouteImport.update({
  id: '/tools/retention-doctor',
  path: '/tools/retention-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRepurposingAssistantRoute =
  ToolsRepurposingAssistantRouteImport.update({
    id: '/tools/repurposing-assistant',
    path: '/tools/repurposing-assistant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsRateCardCalculatorRoute = ToolsRateCardCalculatorRouteImport.update({
  id: '/tools/rate-card-calculator',
  path: '/tools/rate-card-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPinnedCommentRoute = ToolsPinnedCommentRouteImport.update({
  id: '/tools/pinned-comment',
  path: '/tools/pinned-comment',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPhotoCarouselRoute = ToolsPhotoCarouselRouteImport.update({
  id: '/tools/photo-carousel',
  path: '/tools/photo-carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPacingCheckerRoute = ToolsPacingCheckerRouteImport.update({
  id: '/tools/pacing-checker',
  path: '/tools/pacing-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNicheFinderRoute = ToolsNicheFinderRouteImport.update({
  id: '/tools/niche-finder',
  path: '/tools/niche-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMediaKitBuilderRoute = ToolsMediaKitBuilderRouteImport.update({
  id: '/tools/media-kit-builder',
  path: '/tools/media-kit-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLoopCtaBuilderRoute = ToolsLoopCtaBuilderRouteImport.update({
  id: '/tools/loop-cta-builder',
  path: '/tools/loop-cta-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHookRewriterRoute = ToolsHookRewriterRouteImport.update({
  id: '/tools/hook-rewriter',
  path: '/tools/hook-rewriter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHookGeneratorRoute = ToolsHookGeneratorRouteImport.update({
  id: '/tools/hook-generator',
  path: '/tools/hook-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHookAbTesterRoute = ToolsHookAbTesterRouteImport.update({
  id: '/tools/hook-ab-tester',
  path: '/tools/hook-ab-tester',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHashtagPackRoute = ToolsHashtagPackRouteImport.update({
  id: '/tools/hashtag-pack',
  path: '/tools/hashtag-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDuetStitchFinderRoute = ToolsDuetStitchFinderRouteImport.update({
  id: '/tools/duet-stitch-finder',
  path: '/tools/duet-stitch-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsContentCalendarRoute = ToolsContentCalendarRouteImport.update({
  id: '/tools/content-calendar',
  path: '/tools/content-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCommentReplyGeneratorRoute =
  ToolsCommentReplyGeneratorRouteImport.update({
    id: '/tools/comment-reply-generator',
    path: '/tools/comment-reply-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCaptionCrafterRoute = ToolsCaptionCrafterRouteImport.update({
  id: '/tools/caption-crafter',
  path: '/tools/caption-crafter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBioOptimizerRoute = ToolsBioOptimizerRouteImport.update({
  id: '/tools/bio-optimizer',
  path: '/tools/bio-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBestTimeToPostRoute = ToolsBestTimeToPostRouteImport.update({
  id: '/tools/best-time-to-post',
  path: '/tools/best-time-to-post',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBRollSuggesterRoute = ToolsBRollSuggesterRouteImport.update({
  id: '/tools/b-roll-suggester',
  path: '/tools/b-roll-suggester',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools/b-roll-suggester': typeof ToolsBRollSuggesterRoute
  '/tools/best-time-to-post': typeof ToolsBestTimeToPostRoute
  '/tools/bio-optimizer': typeof ToolsBioOptimizerRoute
  '/tools/caption-crafter': typeof ToolsCaptionCrafterRoute
  '/tools/comment-reply-generator': typeof ToolsCommentReplyGeneratorRoute
  '/tools/content-calendar': typeof ToolsContentCalendarRoute
  '/tools/duet-stitch-finder': typeof ToolsDuetStitchFinderRoute
  '/tools/hashtag-pack': typeof ToolsHashtagPackRoute
  '/tools/hook-ab-tester': typeof ToolsHookAbTesterRoute
  '/tools/hook-generator': typeof ToolsHookGeneratorRoute
  '/tools/hook-rewriter': typeof ToolsHookRewriterRoute
  '/tools/loop-cta-builder': typeof ToolsLoopCtaBuilderRoute
  '/tools/media-kit-builder': typeof ToolsMediaKitBuilderRoute
  '/tools/niche-finder': typeof ToolsNicheFinderRoute
  '/tools/pacing-checker': typeof ToolsPacingCheckerRoute
  '/tools/photo-carousel': typeof ToolsPhotoCarouselRoute
  '/tools/pinned-comment': typeof ToolsPinnedCommentRoute
  '/tools/rate-card-calculator': typeof ToolsRateCardCalculatorRoute
  '/tools/repurposing-assistant': typeof ToolsRepurposingAssistantRoute
  '/tools/retention-doctor': typeof ToolsRetentionDoctorRoute
  '/tools/script-writer': typeof ToolsScriptWriterRoute
  '/tools/seo-description': typeof ToolsSeoDescriptionRoute
  '/tools/series-namer': typeof ToolsSeriesNamerRoute
  '/tools/sponsorship-pitch': typeof ToolsSponsorshipPitchRoute
  '/tools/storytime-builder': typeof ToolsStorytimeBuilderRoute
  '/tools/thumbnail-designer': typeof ToolsThumbnailDesignerRoute
  '/tools/thumbnail-text': typeof ToolsThumbnailTextRoute
  '/tools/trend-angles': typeof ToolsTrendAnglesRoute
  '/tools/video-ideas': typeof ToolsVideoIdeasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools/b-roll-suggester': typeof ToolsBRollSuggesterRoute
  '/tools/best-time-to-post': typeof ToolsBestTimeToPostRoute
  '/tools/bio-optimizer': typeof ToolsBioOptimizerRoute
  '/tools/caption-crafter': typeof ToolsCaptionCrafterRoute
  '/tools/comment-reply-generator': typeof ToolsCommentReplyGeneratorRoute
  '/tools/content-calendar': typeof ToolsContentCalendarRoute
  '/tools/duet-stitch-finder': typeof ToolsDuetStitchFinderRoute
  '/tools/hashtag-pack': typeof ToolsHashtagPackRoute
  '/tools/hook-ab-tester': typeof ToolsHookAbTesterRoute
  '/tools/hook-generator': typeof ToolsHookGeneratorRoute
  '/tools/hook-rewriter': typeof ToolsHookRewriterRoute
  '/tools/loop-cta-builder': typeof ToolsLoopCtaBuilderRoute
  '/tools/media-kit-builder': typeof ToolsMediaKitBuilderRoute
  '/tools/niche-finder': typeof ToolsNicheFinderRoute
  '/tools/pacing-checker': typeof ToolsPacingCheckerRoute
  '/tools/photo-carousel': typeof ToolsPhotoCarouselRoute
  '/tools/pinned-comment': typeof ToolsPinnedCommentRoute
  '/tools/rate-card-calculator': typeof ToolsRateCardCalculatorRoute
  '/tools/repurposing-assistant': typeof ToolsRepurposingAssistantRoute
  '/tools/retention-doctor': typeof ToolsRetentionDoctorRoute
  '/tools/script-writer': typeof ToolsScriptWriterRoute
  '/tools/seo-description': typeof ToolsSeoDescriptionRoute
  '/tools/series-namer': typeof ToolsSeriesNamerRoute
  '/tools/sponsorship-pitch': typeof ToolsSponsorshipPitchRoute
  '/tools/storytime-builder': typeof ToolsStorytimeBuilderRoute
  '/tools/thumbnail-designer': typeof ToolsThumbnailDesignerRoute
  '/tools/thumbnail-text': typeof ToolsThumbnailTextRoute
  '/tools/trend-angles': typeof ToolsTrendAnglesRoute
  '/tools/video-ideas': typeof ToolsVideoIdeasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools/b-roll-suggester': typeof ToolsBRollSuggesterRoute
  '/tools/best-time-to-post': typeof ToolsBestTimeToPostRoute
  '/tools/bio-optimizer': typeof ToolsBioOptimizerRoute
  '/tools/caption-crafter': typeof ToolsCaptionCrafterRoute
  '/tools/comment-reply-generator': typeof ToolsCommentReplyGeneratorRoute
  '/tools/content-calendar': typeof ToolsContentCalendarRoute
  '/tools/duet-stitch-finder': typeof ToolsDuetStitchFinderRoute
  '/tools/hashtag-pack': typeof ToolsHashtagPackRoute
  '/tools/hook-ab-tester': typeof ToolsHookAbTesterRoute
  '/tools/hook-generator': typeof ToolsHookGeneratorRoute
  '/tools/hook-rewriter': typeof ToolsHookRewriterRoute
  '/tools/loop-cta-builder': typeof ToolsLoopCtaBuilderRoute
  '/tools/media-kit-builder': typeof ToolsMediaKitBuilderRoute
  '/tools/niche-finder': typeof ToolsNicheFinderRoute
  '/tools/pacing-checker': typeof ToolsPacingCheckerRoute
  '/tools/photo-carousel': typeof ToolsPhotoCarouselRoute
  '/tools/pinned-comment': typeof ToolsPinnedCommentRoute
  '/tools/rate-card-calculator': typeof ToolsRateCardCalculatorRoute
  '/tools/repurposing-assistant': typeof ToolsRepurposingAssistantRoute
  '/tools/retention-doctor': typeof ToolsRetentionDoctorRoute
  '/tools/script-writer': typeof ToolsScriptWriterRoute
  '/tools/seo-description': typeof ToolsSeoDescriptionRoute
  '/tools/series-namer': typeof ToolsSeriesNamerRoute
  '/tools/sponsorship-pitch': typeof ToolsSponsorshipPitchRoute
  '/tools/storytime-builder': typeof ToolsStorytimeBuilderRoute
  '/tools/thumbnail-designer': typeof ToolsThumbnailDesignerRoute
  '/tools/thumbnail-text': typeof ToolsThumbnailTextRoute
  '/tools/trend-angles': typeof ToolsTrendAnglesRoute
  '/tools/video-ideas': typeof ToolsVideoIdeasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/tools/b-roll-suggester'
    | '/tools/best-time-to-post'
    | '/tools/bio-optimizer'
    | '/tools/caption-crafter'
    | '/tools/comment-reply-generator'
    | '/tools/content-calendar'
    | '/tools/duet-stitch-finder'
    | '/tools/hashtag-pack'
    | '/tools/hook-ab-tester'
    | '/tools/hook-generator'
    | '/tools/hook-rewriter'
    | '/tools/loop-cta-builder'
    | '/tools/media-kit-builder'
    | '/tools/niche-finder'
    | '/tools/pacing-checker'
    | '/tools/photo-carousel'
    | '/tools/pinned-comment'
    | '/tools/rate-card-calculator'
    | '/tools/repurposing-assistant'
    | '/tools/retention-doctor'
    | '/tools/script-writer'
    | '/tools/seo-description'
    | '/tools/series-namer'
    | '/tools/sponsorship-pitch'
    | '/tools/storytime-builder'
    | '/tools/thumbnail-designer'
    | '/tools/thumbnail-text'
    | '/tools/trend-angles'
    | '/tools/video-ideas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/tools/b-roll-suggester'
    | '/tools/best-time-to-post'
    | '/tools/bio-optimizer'
    | '/tools/caption-crafter'
    | '/tools/comment-reply-generator'
    | '/tools/content-calendar'
    | '/tools/duet-stitch-finder'
    | '/tools/hashtag-pack'
    | '/tools/hook-ab-tester'
    | '/tools/hook-generator'
    | '/tools/hook-rewriter'
    | '/tools/loop-cta-builder'
    | '/tools/media-kit-builder'
    | '/tools/niche-finder'
    | '/tools/pacing-checker'
    | '/tools/photo-carousel'
    | '/tools/pinned-comment'
    | '/tools/rate-card-calculator'
    | '/tools/repurposing-assistant'
    | '/tools/retention-doctor'
    | '/tools/script-writer'
    | '/tools/seo-description'
    | '/tools/series-namer'
    | '/tools/sponsorship-pitch'
    | '/tools/storytime-builder'
    | '/tools/thumbnail-designer'
    | '/tools/thumbnail-text'
    | '/tools/trend-angles'
    | '/tools/video-ideas'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/tools/b-roll-suggester'
    | '/tools/best-time-to-post'
    | '/tools/bio-optimizer'
    | '/tools/caption-crafter'
    | '/tools/comment-reply-generator'
    | '/tools/content-calendar'
    | '/tools/duet-stitch-finder'
    | '/tools/hashtag-pack'
    | '/tools/hook-ab-tester'
    | '/tools/hook-generator'
    | '/tools/hook-rewriter'
    | '/tools/loop-cta-builder'
    | '/tools/media-kit-builder'
    | '/tools/niche-finder'
    | '/tools/pacing-checker'
    | '/tools/photo-carousel'
    | '/tools/pinned-comment'
    | '/tools/rate-card-calculator'
    | '/tools/repurposing-assistant'
    | '/tools/retention-doctor'
    | '/tools/script-writer'
    | '/tools/seo-description'
    | '/tools/series-namer'
    | '/tools/sponsorship-pitch'
    | '/tools/storytime-builder'
    | '/tools/thumbnail-designer'
    | '/tools/thumbnail-text'
    | '/tools/trend-angles'
    | '/tools/video-ideas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolsBRollSuggesterRoute: typeof ToolsBRollSuggesterRoute
  ToolsBestTimeToPostRoute: typeof ToolsBestTimeToPostRoute
  ToolsBioOptimizerRoute: typeof ToolsBioOptimizerRoute
  ToolsCaptionCrafterRoute: typeof ToolsCaptionCrafterRoute
  ToolsCommentReplyGeneratorRoute: typeof ToolsCommentReplyGeneratorRoute
  ToolsContentCalendarRoute: typeof ToolsContentCalendarRoute
  ToolsDuetStitchFinderRoute: typeof ToolsDuetStitchFinderRoute
  ToolsHashtagPackRoute: typeof ToolsHashtagPackRoute
  ToolsHookAbTesterRoute: typeof ToolsHookAbTesterRoute
  ToolsHookGeneratorRoute: typeof ToolsHookGeneratorRoute
  ToolsHookRewriterRoute: typeof ToolsHookRewriterRoute
  ToolsLoopCtaBuilderRoute: typeof ToolsLoopCtaBuilderRoute
  ToolsMediaKitBuilderRoute: typeof ToolsMediaKitBuilderRoute
  ToolsNicheFinderRoute: typeof ToolsNicheFinderRoute
  ToolsPacingCheckerRoute: typeof ToolsPacingCheckerRoute
  ToolsPhotoCarouselRoute: typeof ToolsPhotoCarouselRoute
  ToolsPinnedCommentRoute: typeof ToolsPinnedCommentRoute
  ToolsRateCardCalculatorRoute: typeof ToolsRateCardCalculatorRoute
  ToolsRepurposingAssistantRoute: typeof ToolsRepurposingAssistantRoute
  ToolsRetentionDoctorRoute: typeof ToolsRetentionDoctorRoute
  ToolsScriptWriterRoute: typeof ToolsScriptWriterRoute
  ToolsSeoDescriptionRoute: typeof ToolsSeoDescriptionRoute
  ToolsSeriesNamerRoute: typeof ToolsSeriesNamerRoute
  ToolsSponsorshipPitchRoute: typeof ToolsSponsorshipPitchRoute
  ToolsStorytimeBuilderRoute: typeof ToolsStorytimeBuilderRoute
  ToolsThumbnailDesignerRoute: typeof ToolsThumbnailDesignerRoute
  ToolsThumbnailTextRoute: typeof ToolsThumbnailTextRoute
  ToolsTrendAnglesRoute: typeof ToolsTrendAnglesRoute
  ToolsVideoIdeasRoute: typeof ToolsVideoIdeasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/video-ideas': {
      id: '/tools/video-ideas'
      path: '/tools/video-ideas'
      fullPath: '/tools/video-ideas'
      preLoaderRoute: typeof ToolsVideoIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/trend-angles': {
      id: '/tools/trend-angles'
      path: '/tools/trend-angles'
      fullPath: '/tools/trend-angles'
      preLoaderRoute: typeof ToolsTrendAnglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/thumbnail-text': {
      id: '/tools/thumbnail-text'
      path: '/tools/thumbnail-text'
      fullPath: '/tools/thumbnail-text'
      preLoaderRoute: typeof ToolsThumbnailTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/thumbnail-designer': {
      id: '/tools/thumbnail-designer'
      path: '/tools/thumbnail-designer'
      fullPath: '/tools/thumbnail-designer'
      preLoaderRoute: typeof ToolsThumbnailDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/storytime-builder': {
      id: '/tools/storytime-builder'
      path: '/tools/storytime-builder'
      fullPath: '/tools/storytime-builder'
      preLoaderRoute: typeof ToolsStorytimeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/sponsorship-pitch': {
      id: '/tools/sponsorship-pitch'
      path: '/tools/sponsorship-pitch'
      fullPath: '/tools/sponsorship-pitch'
      preLoaderRoute: typeof ToolsSponsorshipPitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/series-namer': {
      id: '/tools/series-namer'
      path: '/tools/series-namer'
      fullPath: '/tools/series-namer'
      preLoaderRoute: typeof ToolsSeriesNamerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/seo-description': {
      id: '/tools/seo-description'
      path: '/tools/seo-description'
      fullPath: '/tools/seo-description'
      preLoaderRoute: typeof ToolsSeoDescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/script-writer': {
      id: '/tools/script-writer'
      path: '/tools/script-writer'
      fullPath: '/tools/script-writer'
      preLoaderRoute: typeof ToolsScriptWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/retention-doctor': {
      id: '/tools/retention-doctor'
      path: '/tools/retention-doctor'
      fullPath: '/tools/retention-doctor'
      preLoaderRoute: typeof ToolsRetentionDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/repurposing-assistant': {
      id: '/tools/repurposing-assistant'
      path: '/tools/repurposing-assistant'
      fullPath: '/tools/repurposing-assistant'
      preLoaderRoute: typeof ToolsRepurposingAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rate-card-calculator': {
      id: '/tools/rate-card-calculator'
      path: '/tools/rate-card-calculator'
      fullPath: '/tools/rate-card-calculator'
      preLoaderRoute: typeof ToolsRateCardCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pinned-comment': {
      id: '/tools/pinned-comment'
      path: '/tools/pinned-comment'
      fullPath: '/tools/pinned-comment'
      preLoaderRoute: typeof ToolsPinnedCommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/photo-carousel': {
      id: '/tools/photo-carousel'
      path: '/tools/photo-carousel'
      fullPath: '/tools/photo-carousel'
      preLoaderRoute: typeof ToolsPhotoCarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pacing-checker': {
      id: '/tools/pacing-checker'
      path: '/tools/pacing-checker'
      fullPath: '/tools/pacing-checker'
      preLoaderRoute: typeof ToolsPacingCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/niche-finder': {
      id: '/tools/niche-finder'
      path: '/tools/niche-finder'
      fullPath: '/tools/niche-finder'
      preLoaderRoute: typeof ToolsNicheFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/media-kit-builder': {
      id: '/tools/media-kit-builder'
      path: '/tools/media-kit-builder'
      fullPath: '/tools/media-kit-builder'
      preLoaderRoute: typeof ToolsMediaKitBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/loop-cta-builder': {
      id: '/tools/loop-cta-builder'
      path: '/tools/loop-cta-builder'
      fullPath: '/tools/loop-cta-builder'
      preLoaderRoute: typeof ToolsLoopCtaBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hook-rewriter': {
      id: '/tools/hook-rewriter'
      path: '/tools/hook-rewriter'
      fullPath: '/tools/hook-rewriter'
      preLoaderRoute: typeof ToolsHookRewriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hook-generator': {
      id: '/tools/hook-generator'
      path: '/tools/hook-generator'
      fullPath: '/tools/hook-generator'
      preLoaderRoute: typeof ToolsHookGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hook-ab-tester': {
      id: '/tools/hook-ab-tester'
      path: '/tools/hook-ab-tester'
      fullPath: '/tools/hook-ab-tester'
      preLoaderRoute: typeof ToolsHookAbTesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hashtag-pack': {
      id: '/tools/hashtag-pack'
      path: '/tools/hashtag-pack'
      fullPath: '/tools/hashtag-pack'
      preLoaderRoute: typeof ToolsHashtagPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/duet-stitch-finder': {
      id: '/tools/duet-stitch-finder'
      path: '/tools/duet-stitch-finder'
      fullPath: '/tools/duet-stitch-finder'
      preLoaderRoute: typeof ToolsDuetStitchFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/content-calendar': {
      id: '/tools/content-calendar'
      path: '/tools/content-calendar'
      fullPath: '/tools/content-calendar'
      preLoaderRoute: typeof ToolsContentCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/comment-reply-generator': {
      id: '/tools/comment-reply-generator'
      path: '/tools/comment-reply-generator'
      fullPath: '/tools/comment-reply-generator'
      preLoaderRoute: typeof ToolsCommentReplyGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/caption-crafter': {
      id: '/tools/caption-crafter'
      path: '/tools/caption-crafter'
      fullPath: '/tools/caption-crafter'
      preLoaderRoute: typeof ToolsCaptionCrafterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/bio-optimizer': {
      id: '/tools/bio-optimizer'
      path: '/tools/bio-optimizer'
      fullPath: '/tools/bio-optimizer'
      preLoaderRoute: typeof ToolsBioOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/best-time-to-post': {
      id: '/tools/best-time-to-post'
      path: '/tools/best-time-to-post'
      fullPath: '/tools/best-time-to-post'
      preLoaderRoute: typeof ToolsBestTimeToPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/b-roll-suggester': {
      id: '/tools/b-roll-suggester'
      path: '/tools/b-roll-suggester'
      fullPath: '/tools/b-roll-suggester'
      preLoaderRoute: typeof ToolsBRollSuggesterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolsBRollSuggesterRoute: ToolsBRollSuggesterRoute,
  ToolsBestTimeToPostRoute: ToolsBestTimeToPostRoute,
  ToolsBioOptimizerRoute: ToolsBioOptimizerRoute,
  ToolsCaptionCrafterRoute: ToolsCaptionCrafterRoute,
  ToolsCommentReplyGeneratorRoute: ToolsCommentReplyGeneratorRoute,
  ToolsContentCalendarRoute: ToolsContentCalendarRoute,
  ToolsDuetStitchFinderRoute: ToolsDuetStitchFinderRoute,
  ToolsHashtagPackRoute: ToolsHashtagPackRoute,
  ToolsHookAbTesterRoute: ToolsHookAbTesterRoute,
  ToolsHookGeneratorRoute: ToolsHookGeneratorRoute,
  ToolsHookRewriterRoute: ToolsHookRewriterRoute,
  ToolsLoopCtaBuilderRoute: ToolsLoopCtaBuilderRoute,
  ToolsMediaKitBuilderRoute: ToolsMediaKitBuilderRoute,
  ToolsNicheFinderRoute: ToolsNicheFinderRoute,
  ToolsPacingCheckerRoute: ToolsPacingCheckerRoute,
  ToolsPhotoCarouselRoute: ToolsPhotoCarouselRoute,
  ToolsPinnedCommentRoute: ToolsPinnedCommentRoute,
  ToolsRateCardCalculatorRoute: ToolsRateCardCalculatorRoute,
  ToolsRepurposingAssistantRoute: ToolsRepurposingAssistantRoute,
  ToolsRetentionDoctorRoute: ToolsRetentionDoctorRoute,
  ToolsScriptWriterRoute: ToolsScriptWriterRoute,
  ToolsSeoDescriptionRoute: ToolsSeoDescriptionRoute,
  ToolsSeriesNamerRoute: ToolsSeriesNamerRoute,
  ToolsSponsorshipPitchRoute: ToolsSponsorshipPitchRoute,
  ToolsStorytimeBuilderRoute: ToolsStorytimeBuilderRoute,
  ToolsThumbnailDesignerRoute: ToolsThumbnailDesignerRoute,
  ToolsThumbnailTextRoute: ToolsThumbnailTextRoute,
  ToolsTrendAnglesRoute: ToolsTrendAnglesRoute,
  ToolsVideoIdeasRoute: ToolsVideoIdeasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
